---
contentdir: "content"
layoutdir: "layouts"
disqusShortname: "parasquid"
taxonomies:
  category: "categories"
baseurl: "http://life.beyondrails.com"
title: "Life Beyond Rails"
MetaDataFormat: "yaml"
permalinks:
  post: "/blog/:year/:month/:day/:title/"
params:
  # Used when a given page doesn't set its own.
  defaultDescription: "Your default page description"
  defaultKeywords: "your,default,page,keywords"

  # Changes sidebar background and link/accent colours.
  # See below for more colour options.
  # This also works: "theme-base-08 layout-reverse", or just "layout-reverse".
  theme: "theme-base-0b"

  # Select a syntax highight.
  # Check the static/css/highlight directory for options.
  highlight: "sunburst"

  # Displays under the author name in the sidebar, keep it short.
  tagline: "Codesmith by day. Airsculptor by night."

  # Metadata used to drive integrations.
  googleAuthorship: "Your Google+ profile ID"
  googleAnalytics: "Your Google Analytics tracking code"
  gravatarHash: "e00d9254088a9db2e1875fc324402e2c"

  # Sidebar social links, avoid enabling too many of these if possible.
  # These should be full URLs.
  github: "https://github.com/parasquid"
  linkedin: ""
  googleplus: ""
  facebook: ""
  twitter: "https://twitter.com/parasquid"
---
